version: '2'

services:
    php54:
        build:
            context: .
            dockerfile: ./php54/Dockerfile
        restart: always
        volumes:
            - ./config/php54/www.conf:/opt/remi/php54/root/etc/php-fpm.d/www.conf
            - ./var/logs/php54/php-fpm:/opt/remi/php54/root/var/log/php-fpm:rw
            - ./var/logs/php54/lib:/www/logs/lib:rw
            - ./www/logs/lib:/www/logs/lib:rw
            - ./www/logs/oauth:/www/logs/oauth:rw
            - ./var/www/sites:/var/www/sites:rw
        working_dir: /var/www/sites
    php56:
        build:
            context: .
            dockerfile: ./php56/Dockerfile
        restart: always
        volumes:
            - ./config/php54/www.conf:/opt/remi/php56/root/etc/php-fpm.d/www.conf
            - ./var/logs/php56/php-fpm:/opt/remi/php56/root/var/log/php-fpm:rw
            - ./var/logs/php56/lib:/www/logs/lib:rw
            - ./www/logs/lib:/www/logs/lib:rw
            - ./www/logs/oauth:/www/logs/oauth:rw
            - ./var/www/sites:/var/www/sites:rw
        working_dir: /var/www/sites
    php71:
        build:
            context: .
            dockerfile: ./php71/Dockerfile
        restart: always
        volumes:
            - ./config/php54/www.conf:/opt/remi/php71/root/etc/php-fpm.d/www.conf
            - ./var/logs/php71/php-fpm:/opt/remi/php71/root/var/log/php-fpm:rw
            - ./var/logs/php71/lib:/www/logs/lib:rw
            - ./www/logs/lib:/www/logs/lib:rw
            - ./www/logs/oauth:/www/logs/oauth:rw
            - ./var/www/sites:/var/www/sites:rw
        working_dir: /var/www/sites
    proxy:
        image: nginx:latest
        restart: always
        ports:
            - "80:80"
        depends_on:
            - php54
            - php56
            - php71
        links:
            - php54
            - php56
            - php71
        volumes:
            - ./config/nginx/sites.conf:/etc/nginx/conf.d/sites.conf
            - ./config/nginx/mpgu.common:/etc/nginx/conf.d/mpgu.common
            - ./var/logs/nginx:/var/logs/nginx:rw
            - ./var/www/sites:/var/www/sites:rw
